import images from "./images";
import icons from "./icons";

const restaurants = [
  {
    id: 1,
    name: "The Black Whale",
    address: "106 MacArthur Dr, New Bedford, MA 02740",
    phone: "(508) 990-7100",
    hours:
      "Monday - Thursday 11:30am - 9pm\nFriday & Saturday 11:30am - 10pm\nSunday 11:30am - 9pm",
    category: "Seafood",
    alternateCategory: "Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$$",
    spiceLevel: 2,
    rating: 5,
    menu: "https://www.theblackwhale.com/menus/",
    website: "https://www.theblackwhale.com/",
    coordinates: [41.637130986176764, -70.92110706438882],
    about:
      "The Black Whale was created by New Bedford locals to honor the seafaring heritage of New Bedford and the world-famous seafood bounty landed in its port. The Black Whale is designed to be an innovative seafood kitchen with a great bar. Our food mission is to serve fresh, bold, and innovative food that reflects the history of New Bedford and celebrates the New Bedford fishermen, their catch and their culture. ",
  },
  {
    id: 2,
    name: "The Pour Farm Tavern",
    address: "780 Purchase St, New Bedford, MA 02740",
    phone: "(508) 990-1123",
    hours:
      "Tuesday 4pm - 2am\nWednesday - Saturday 12pm - 2am\nSunday 11am - 2am",
    category: "American",
    alternateCategory: "Pub | Brunch | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 4,
    menu: "https://pourfarm.com/",
    website: "https://pourfarm.com/",
    coordinates: [41.63573367510729, -70.92574949153057],
    about:
      "Patrons turned owners, Brad and Jen Cardoza own and operate The Pour Farm, located at 780 Purchase Street in New Bedford. Striving to educate the public on the wonderous world craft beers and enlighten the pallet to the culinary world that runs parallel to it, they foster an environment to promotes knowledge as much as it does a fun night out for friends. Creating this environment as Brad says ensure that, “There’s something for all”.",
  },
  {
    id: 3,
    name: "BesTeas Bubble Tea",
    address: "498 Pleasant St, New Bedford, MA 02740",
    phone: "(774) 425-2052",
    hours: "Monday - Saturday 9am - 5pm\nSunday 9am - 3pm",
    category: "Cafe",
    alternateCategory: "",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 1,
    rating: 3,
    menu: "https://besteasbubbletea.com/menu-1",
    website: "https://besteasbubbletea.com/",
    coordinates: [41.633712317990735, -70.9265233037926],
    about:
      "Allie and Barbara are the tea fanatics behind the New Bedford sensation, BesTeas. Friends and coworkers for over 15 tears, in 2019 they decided to make their love for bubble tea into a lifestyle. Barbara and Allie traveled to California to attend a bob academy where they learned the ins and outs of boba tea and perfected their craft to bring it to the south shore.",
  },
  {
    id: 4,
    name: "Moby Dick Brewing Co.",
    address: "16 S Water St, New Bedford, MA 02740",
    phone: "(774) 202-6961",
    hours:
      "Monday - Thursday 11:30am - 9pm\nFriday & Saturday 11:30am - 10pm\nSunday 11:30am - 8pm",
    category: "Pub | American",
    alternateCategory: " Vegan | Seafood | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 4,
    menu: "https://www.mobydickbrewing.com/dinner-menu/",
    website: "https://www.mobydickbrewing.com/",
    coordinates: [41.634542978682525, -70.92260533077281],
    about:
      "At Moby Dick Brewing Co., we honor New Bedford’s storied history. More importantly, we celebrate what New Bedford is and what it is becoming: America’s most important fishing port and a home port for America’s newest alternative energy industry — offshore wind, as well as a bustling arts and cultural district.",
  },
  {
    id: 5,
    name: "Carmines at Candleworks",
    address: "72 N Water St, New Bedford, MA 02740",
    phone: "(774) 510-7901",
    hours:
      "Monday - Thursday 11:30am - 9pm\nFriday & Saturday 11:30am - 10pm\nSunday 11am - 9pm",
    category: "Italian",
    alternateCategory: "Brunch | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://carminesatcandleworks.com/our-complete-menu/",
    website: "https://carminesatcandleworks.com/",
    coordinates: [41.636169023643255, -70.92274167309964],
    about:
      "When you imagine a rustic Italian restaurant, indulgent sauces and robust flavors come to mind. At Carmine’s at Candleworks, we offer just that. Our kitchen in New Bedford, MA prepares our menu items using fresh, top-quality ingredients every day.",
  },
  {
    id: 6,
    name: "Tia Maria's European Café",
    address: "42 N Water St, New Bedford, MA 02740",
    phone: "(508) 993-8900",
    hours:
      "Monday - Thursday 8am - 2pm\nFriday & Saturday 8am - 8pm\nSunday 8am - 1pm",
    category: "Portuguese",
    alternateCategory: "Breakfast | Brunch | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 2,
    menu: "http://www.tiamariaseuropeancafe.com/menu.html",
    website: "http://www.tiamariaseuropeancafe.com/",
    coordinates: [41.635573988216564, -70.92281303262912],
    about:
      "Located in the heart of the National Historical Whaling Park along the cobblestone streets of historic downtown New Bedford, Tia Maria's European Café opened in September of 2013. Tia Maria's is a food centric Portuguese family-owned restaurant where we greet our customers by name. All our dishes are made to order, and we use local and organic ingredients whenever possible.",
  },

  {
    id: 7,
    name: "Quahog Republic",
    address: "24 N Water St, New Bedford, MA 02740",
    phone: "(774) 206-6303",
    hours:
      "Sun, Mon, Wed & Thurs: 11:30am - 11pm\nFriday & Saturday 11:30am - 1am",
    category: "Seafood",
    alternateCategory: "Pub | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://quahogrepublic.com/whalers-menu",
    website: "https://quahogrepublic.com/whalers-tavern/",
    coordinates: [41.64067171520755, -70.92305659523001],
    about:
      "Located in a historic building on the quaint cobblestone streets of downtown New Bedford, we are just a short walk away from the working waterfront of New Bedford. The Whaler's Tavern has the same Quahog Republic vibe as with their other two locations, with a nod to the city's rich seafaring history. Whaler’s Tavern offers a full menu, raw bar, 14 beers on draft, nice wine selection, creatively inspired cocktails and over 20 different varieties of rum. All are encouraged to come and experience a taste of the Quahog Republic flair with a tip of the hat to The Whaling City.",
  },
  {
    id: 8,
    name: "Ming Sushi",
    address: "774 Purchase St, New Bedford, MA 02740",
    phone: "(508) 999-1113",
    hours: "Mon - Thur: 11am - 3pm, 4:30pm - 9pm\nFri & Sat: 11am - 10pm",
    category: "Sushi | Seafood | Asian",
    alternateCategory: "Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$$",
    spiceLevel: 2,
    rating: 4,
    menu: "http://www.mingsushima.com/menu/1.html",
    website: "http://www.mingsushima.com/",
    coordinates: [41.634932499484066, -70.92582327507435],
    about:
      "Located at 774 Purchase Street in New Bedford, Ming Sushi offers a wide array of authentic Japanese Food: such as Hibachi Steak, Chicken Katsu, Tuna Roll, Sushi & Sashimi Combo, Tempura Udon, Green Salad, and Miso Soup. Join them for their Japanese Lunch Special or during evenings for a delicious Japanese style dinner. Ming Sushi is always looking to diversify their menu, so any and all suggestions are encouraged through their Customer Feedback Page, and they look forward to seeing you soon!",
  },
  {
    id: 9,
    name: "Cisco Brewers",
    address: "1482 E Rodney French Blvd, New Bedford, MA 02744",
    phone: "(774)-702-4726",
    hours:
      "Sunday - Thursday: 11:30am - 9pm\nFriday & Saturday: 11:30am - 11pm",
    category: "Pub | American",
    alternateCategory: "Seafood | Lunch | Dinner | Sushi | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$$",
    spiceLevel: 2,
    rating: 5,
    menu: "https://www.ciscokitchenbar.com/menus/",
    website: "https://www.ciscokitchenbar.com/",
    coordinates: [41.6107064128793, -70.9057419154272],
    about:
      "An offshoot of the famed Cisco Brewers Nantucket: a buzzing brewery with live music known for being a damn good time, Cisco Brewers New Bedford is a collaborative project between Cisco Brewers and local restauranteur Steve Silverstein. Cisco Brewers New Bedford is a 3.5-acre entertainment complex complete with a restaurant, seven total bars, and daily live music in the summer months. They year-round surf inspired them of Cisco Kitchen and Bar offers a variety of sushi options. Along with water access, Cisco’s acts as a mecca for kicking back, relaxing for those of all ages (especially dogs).",
  },
  {
    id: 10,
    name: "Cork Wine & Tapas",
    address: "90 Front St, New Bedford, MA 02740",
    phone: "(508) 994-9463",
    hours:
      "Monday - Wednesday 4pm - 9pm\nThursday & Sunday 11:30am - 9pm\nFriday & Saturday 11:30am - 11pm",
    category: "American",
    alternateCategory: "Pub | Seafood | Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://www.corkwineandtapas.com/menu",
    website: "https://www.corkwineandtapas.com/",
    coordinates: [41.63506763361584, -70.92195157309962],
  },
  {
    id: 11,
    name: "Brick Pizzeria Napoletana",
    address: "163 Union St, New Bedford, MA 02740",
    phone: "(508) 999-4943",
    hours: "Monday - Saturday 11am - 9pm\nSunday 12pm - 8pm",
    category: "Italian",
    alternateCategory: "Lunch | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://www.pizzeriabrick.com/menu.html",
    website: "https://www.pizzeriabrick.com",
    coordinates: [41.63453016637848, -70.9253917021327],
  },
  {
    id: 12,
    name: "Spicy Lime",
    address: "522 Pleasant St, New Bedford, MA 02740",
    phone: "(508) 992-3330",
    hours: "Tuesday - Saturday 4pm - 9pm",
    category: "Asian American | Thai",
    alternateCategory: "Seafood | Lunch | Dinner | Appetizers | Soups",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 2,
    rating: 3,
    menu: "http://spicylimethai.com/wp-content/uploads/2021/10/spicylimethaimenu2021.pdf",
    website: "http://spicylimethai.com/",
    coordinates: [41.63417323572998, -70.92660650213278],
  },
  {
    id: 13,
    name: "Destination Soups",
    address: "149 Union St, New Bedford, MA 02740",
    phone: "(508) 991-7687",
    hours: "Monday - Friday 11am - 4pm",
    category: "American | Cafe | Soups",
    alternateCategory: "Brunch | Lunch",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://destinationsoups.com/menu/",
    website: "https://destinationsoups.com",
    coordinates: [41.6345386161403, -70.92521615957004],
  },
  {
    id: 14,
    name: "No Problemo",
    address: "813 Purchase St, New Bedford, MA 02740",
    phone: "(508) 984-1081",
    hours: "Monday - Wednesday 11am - 8pm\nThursday - Saturday 11am - 9pm",
    category: "Latinx",
    alternateCategory: "Lunch | Dinner",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 2,
    rating: 3,
    menu: "http://www.menujoy.com/menu89.htm",
    website: "https://www.facebook.com/profile.php?id=100064825985442",
    coordinates: [41.63537397013885, -70.92612807144913],
  },
  {
    id: 15,
    name: "The Baker - New Bedford",
    address: "562 Pleasant St, New Bedford, MA 02740",
    phone: "(774) 202-1901",
    hours: "Wednesday - Friday 7:30am - 2pm\nSaturday & Sunday 8am - 2pm",
    category: "American | Breakfast | Cafe",
    alternateCategory: "Brunch | Lunch | Pasteries",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://thebakernb.com/pastries/",
    website: "https://thebakernb.com",
    coordinates: [41.63472813441836, -70.92679421747467],
  },
  {
    id: 16,
    name: "Rose Alley Ale House",
    address: "94 Front St, New Bedford, MA 02740",
    phone: "(508) 858-5123",
    hours: "Sunday - Friday 11:30am - 2am\nSaturday 9am - 2am",
    category: "American",
    alternateCategory: "Pub | Lunch | Dinner | Pasteries | Appetizers | Soups",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://www.toasttab.com/rose-alley-ale-house/v3/#d79fb96ee-856e-4672-b418-16955a7bb88bd83124989-1a05-4ca7-8c9d-e7d4e4285e19",
    website: "https://rosealleyalehouse.com/about-us/",
    coordinates: [41.63527926358073, -70.9218978865503],
  },
  {
    id: 17,
    name: "Play Arcade",
    address: "34 Union St, New Bedford, MA, 02740",
    phone: "(774) 202-7358",
    hours:
      "Wednesday - Friday 5pm - 12am\nSaturday 12pm - 12am\nSunday 12pm - 9pm\n21+ After 8pm Every Night",
    category: "American",
    alternateCategory: "Pub | Dinner | Appetizers",
    title: "Food",
    logo: require("../assets/logos/bestea_bubble_tea.png"),
    image: images.brick_pizzeria,
    header_image: images.bestea_inside,
    priceRange: "$$",
    spiceLevel: 2,
    rating: 3,
    menu: "https://www.playarcadenb.com/order-food",
    website: "https://www.playarcadenb.com/",
    coordinates: [41.63512493628287, -70.92206520596729],
    about:
      "Play is an old school 80's style arcade owned and operated by local couple, Adam & Lauren Katz.   It features over 40 vintage token-operated arcade games, a full-service bar, craft made drinks and food including delicious vegan and gluten-free selections.  Play also has a roof deck bar overlooking the picturesque harbor.  There's local artwork and nostalgia on every wall and live music during the summer.  Come in and bring your child, or bring out your inner child! There's something for everyone at Play!",
  },
];
const categories = [
  {
    id: 1,
    title: "Food",
    thumbnail: images.brick_pizzeria,
  },
  {
    id: 2,
    title: "Tours",
    thumbnail: images.brick_pizzeria,
  },
];
const foodCrawls = [
  {
    id: 1,
    name: "All American",
    image: images.burger,
    logo: images.burger,
    priceRange: "$$",
    header_image: [
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
    ],
    eateryId: { Drinks: 9, Appetizer: 4, Entree: 2, Dessert: 15 },
    about:
      "American bar food is comforting and makes for great entertainment. Take the time to explore the options New Bedford has to offer! Below are suggestions but feel free to explore different menu options!",
  },
  {
    id: 2,
    name: "Italian",
    image: images.burger,
    logo: images.burger,
    priceRange: "$$",
    header_image: [
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
    ],
    eateryId: { Drinks: "NA", Appetizer: 11, Entree: 5, Dessert: 5 },
    about:
      "This food crawl features Italian cuisine from downtown New Bedford! From brick oven pizza to fresh pasta, you will not regret trying these spots! Below are suggestions but feel free to explore menu options!",
  },
  {
    id: 3,
    name: "Portuguese",
    image: images.burger,
    logo: images.burger,
    priceRange: "$$",
    header_image: [
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
      images.bestea_inside,
    ],
    eateryId: { Drinks: 10, Appetizer: 16, Entree: 6, Dessert: "NA" },
    about:
      "The Portguese food crawl features the Portuguese food offered in downtown! Enjoy food from fuision style restaurants or from a hotspot for Portugese food! Below are suggestions but feel free to explore different menu options",
  },
];

export default {
  restaurants,
  categories,
  foodCrawls,
};
